name: Cub3D CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make xorg libxext-dev libbsd-dev valgrind

    - name: Prepare MiniLibX
      run: |
        cd minilibx-linux-master
        [ -f configure ] && chmod +x configure || echo "Configure script not found, continuing"
        [ -f configure.inc ] && chmod +x configure.inc || echo "Configure.inc not found, continuing"
        cd ..

    - name: Compile project
      run: |
        make re
        ls -la cub3D

    - name: Create test maps directory
      run: |
        mkdir -p maps
        [ ! -f maps/valid_map.cub ] && echo "NO textures/wall.xpm\nF 220,100,0\nC 135,206,235\n111\n1P1\n111" > maps/valid_map.cub
        [ ! -f maps/invalid_map.cub ] && echo "invalid content" > maps/invalid_map.cub

    - name: Basic map validation
      run: |
        ./cub3D maps/invalid_map.cub 2>&1 | grep "Error" || (echo "Map validation failed" && exit 1)
        ./cub3D maps/valid_map.cub 2>&1 | grep "Error" && exit 1 || echo "Valid map accepted"

    - name: Run with Valgrind
      run: |
        mkdir -p logs
        valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 \
        --track-origins=yes --log-file=logs/valgrind.log \
        ./cub3D maps/valid_map.cub || true
        cat logs/valgrind.log

    - name: Output verification
      run: |
        mkdir -p logs
        timeout 5 ./cub3D maps/valid_map.cub > logs/output.log 2>&1 &
        sleep 3
        grep "Initialization complete" logs/output.log || (echo "Startup failed" && exit 1)
        killall cub3D || true

    - name: Upload debug logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: debug-logs
        path: logs/*
        retention-days: 1