name: Cub3D CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make xorg libxext-dev libbsd-dev valgrind

    - name: Compile project
      run: |
        make re
        ls -la cub3D

    - name: Basic map validation
      run: |
        ./cub3D maps/invalid_map.cub 2>&1 | grep "Error" || (echo "Map validation failed" && exit 1)
        ./cub3D maps/valid_map.cub 2>&1 | grep "Error" && exit 1 || echo "Valid map accepted"

    - name: Run with Valgrind
      run: |
        valgrind --leak-check=full --show-leak-kinds=all --error-exitcode=1 \
        --track-origins=yes --log-file=valgrind.log \
        ./cub3D maps/valid_map.cub || true
        cat valgrind.log

    - name: Output verification
      run: |
        timeout 5 ./cub3D maps/valid_map.cub > output.log 2>&1 &
        sleep 3
        grep "Initialization complete" output.log || (echo "Startup failed" && exit 1)
        killall cub3D || true

    - name: Upload debug logs
      if: always() 
      uses: actions/upload-artifact@v4
      with:
        name: debug-logs
        path: |
          output.log
          valgrind.log
        retention-days: 1